# This contains the CL specific constraints for synthesis at the CL level
set_false_path -from [get_cells config_regs/fpgaid_reg*]
set_false_path -from [get_cells config_regs/chip0_base_reg*]
set_false_path -from [get_cells config_regs/chip1_base_reg*]
set_false_path -from [get_cells config_regs/chip2_base_reg*]
set_false_path -from [get_cells config_regs/chip3_base_reg*]
set_false_path -from [get_cells config_regs/chip4_base_reg*]
set_false_path -from [get_cells config_regs/chip5_base_reg*]
set_false_path -from [get_cells config_regs/chip6_base_reg*]
set_false_path -from [get_cells config_regs/chip7_base_reg*]
set_false_path -from [get_cells config_regs/chip8_base_reg*]
set_false_path -from [get_cells config_regs/chip9_base_reg*]
set_false_path -from [get_cells config_regs/chip10_base_reg*]
set_false_path -from [get_cells config_regs/chip11_base_reg*]
set_false_path -from [get_cells config_regs/chip12_base_reg*]
set_false_path -from [get_cells config_regs/chip13_base_reg*]
set_false_path -from [get_cells config_regs/chip14_base_reg*]
set_false_path -from [get_cells config_regs/chip15_base_reg*]
set_false_path -from [get_cells config_regs/host_base_reg*]
set_false_path -from [get_cells *system*/chip/tile*/uncore_config/chipid_reg*]
set_false_path -from [get_cells *system*/chip/tile*/uncore_config/coreid_x_reg*]
set_false_path -from [get_cells *system*/chip/tile*/uncore_config/coreid_y_reg*]
set_false_path -from [get_cells -hierarchical *ui_clk_sync_rst*]
set_false_path -from [get_cells -hierarchical *init_calib_complete_ff*]
set_false_path -from [get_cells -hierarchical *chipset_rst_n*]
set_false_path -from [get_cells -hierarchical piton_rst_n*]
set_false_path -from [get_cells -hierarchical shell_rst_n*]
set_false_path -from [get_cells -hierarchical interconnect_rst_n*]
